[WIP] Enqueuing installer help pages for checking
datawire/getambassador.io-blc pull request #10
Opened 2020-04-07 19:45 UTC by khussey

Explicitly enqueuing the installer help files (new as of 1.4) to be checked (since they are currently only referenced by the installer, not by any other pages on the site).

2020-04-07 19:50 UTC, kflynn requested changes
Holy crap. Think there are enough of them? 

Also: probably best to start off with `docs/1.4` rather than `docs/latest`. The preview docs don't show up under `docs/latest`.

2020-04-07 20:20 UTC, khussey commented
@kflynn preview docs should show up under docs/latest (once we've configured docs properly). My thinking is we'd merge this changes AFTER we've shipped 1.4 anyway (since checking would fail for PRs not against the release/v1.4 branch until we ship).

I'm hoping that we can add a "troubleshooting" page of some sort in the future which will reference these new pages and obviate the need to check them explicitly...

2020-04-07 21:49 UTC, kflynn commented
Merging after shipping sounds great.

2020-04-08 21:17 UTC, khussey commented
These changes are obviated by https://github.com/datawire/ambassador/pull/2559 (which plugs the help pages into the TOC via an index page).

2020-04-08 21:17 UTC, closed without merging